/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const express = require('express');
const bodyParser = require('body-parser');
// const path = require('path');
const app = express();
const port = 3000;

app.use(bodyParser.json());

const todos = [
  {
    id: 1,
    title: "Az-900",
    completed: false
  },
  {
    id: 2,
    title: "Express.Js",
    completed: true
  }
];

function isDoTOPresent(todoId) {
  return todos.some(i => i.id == todoId)
}

app.get('/todos', (req, res) => {
  if (todos.length == 0) {
    res.status(404).json({
      msg: "Bhai ek nhi todo list task nahi hai"
    });
  }
  else {
    res.status(200).send(todos);
  }
});

app.get('/todos/:id', (req, res) => {

  const todoId = parseInt(req.params.id);

  if (!isDoTOPresent(todoId)) {
    res.status(404).json({
      msg: "Bhai todo list mai nahi hai ye id"
    });
  }
  else {
    const todoById = todos.find(i => i.id === todoId);
    res.status(200).send(todoById);
  }
});

// app.post('/todos', (req, res) => {
//   if (!req.body) {
//     res.status(411).json({
//       msg: "bhai achese input de json mai"
//     });
//   } else {
//     const newTODO = req.body;
//     todos.push(newTODO);
//     res.status(201).json({
//       msg: 'Le bhai, kar diya add'
//     });
//   }
// });

let nextId = todos.length ? Math.max(...todos.map(todo => todo.id)) + 1 : 1;

app.post('/todos', (req, res) => {
  const { title, completed } = req.body;

  if (!title) {
    return res.status(400).json({ msg: "bhai,Title and description are required" });
  }

  const newTODO = {
    id: nextId++,
    title,
    completed: completed || false
  };

  todos.push(newTODO);
  res.status(201).json({
    id: newTODO.id,
    msg: "Kar diya bhai add"
  });
});

app.put('/todos/:id', (req, res) => {
  const todoId = parseInt(req.params.id);

  if (!isDoTOPresent(todoId)) {
    res.status(404).json({
      msg: "bhai tune jo id diya hai wo exist hi nahi krta"
    });
  } else {
    const updateToDo = req.body;
    const index = todos.findIndex(i => i.id == todoId);
    todos[index] = { ...todos[index], ...updateToDo }   //smart way using spread operator
    //manual way
    // todos[index].title = updateToDo.title;
    // todos[index].completed = updateToDo.completed;

    res.status(200).json({
      msg: "Kar diya bhai update, khush reh"
    });
  }
});

app.delete('/todos/:id', (req, res) => {

  const todoId = parseInt(req.params.id);

  if (!isDoTOPresent(todoId)) {
    res.status(404).json({
      msg: 'Bhai wo id hi present nahi hai'
    });
  }
  else {
    const index = todos.findIndex(i => i.id == todoId);
    todos.splice(index, 1);
    res.status(200).json({
      msg: "Ho gaya delete"
    });
  }
});

app.use((req, res) => {
  res.status(404).json({ msg: "Bhai ye route hi nahi hai" });
});

app.listen(port, () => { console.log(`Running on port ${port}`) });

module.exports = app;